#
# https://alacritty.org/config-alacritty.html
#

[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]

# make sure I can type '#' easily
[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[window]
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"

[font]
size = 17

[font.bold]
family = "JetBrainsMonoNL NFP"
style = "Light"

[font.normal]
family = "JetBrainsMonoNL NFP"
style = "Light"

[window.padding]
x = 0
y = 0

[mouse]
hide_when_typing = true

