#!/bin/zsh
#
# Add following <F12> key binding to this into ~/.zshrc:
# bindkey -s '^[[24~' '~/bin/links \C-m'
#
# Another option: set F12 key binding in tmux:
# bind-key -n F12 split-window -v 'bash ~/bin/links'

URL=$(cat ~/Dropbox/xzhong-links.txt | fzf +s -e | awk '{print $2}')
if [ -z "$URL" ];
then
  echo
else
  # MacOS
  open -a Google\ Chrome $URL
  # Windows: explorer.exe $URL
  # Write in ~/.bashrc: bind '"\e[24~":"bash ~/bin/links\n"'
fi
